plugins { id 'com.android.application' }

android {
    namespace 'com.vuizcomm.frontier'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vuizcomm.frontier'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}
